### ISSUE TITLE
Well It finally happened :-(

### ISSUE THREAD

**Issue by jayrodathome** [kensleDev/Rocket-League-Custom-Quickchat#3]
Oops I think this is the wrong git. Sorry

**Comment by kensleDev** [comment]
Thanks for letting me know,

I haven't been using it for a while as I was using a pad with paddles which
broke but have just got a new one so may see what I can do. I really do
appreciate it I've had a couple of emails but wasn't sure if people were
even using it.

I will update the repo soon just streaming at the moment but if u fancy
some games anytime  I'm bmfnjuju#6139

Thanks again

**Comment by kensleDev** [comment]
Oh wow I've not seen the email that's in the trail to this one.

This is an older account that I just hooked up again the other day and
.......

WTF

I'm so sorry that happened to you...


When I use it I leave it on all the time but haven't played many other
games. I did read up on of ahk is allowed in games and should have but a
disclaimer on the repo...


I hope it hasn't cost you any more games in the meantime!
